In [2]:
import nltk
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /home/pekasus/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [4]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /home/pekasus/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [5]:
lemmatizer = WordNetLemmatizer()

In [6]:
sentence = 'Vegetables are types of plants.'
sentence_tokens = nltk.word_tokenize(sentence.lower())
sentence_tokens

['vegetables', 'are', 'types', 'of', 'plants', '.']

In [7]:
pos_tags = nltk.pos_tag(sentence_tokens)
pos_tags

[('vegetables', 'NNS'),
 ('are', 'VBP'),
 ('types', 'NNS'),
 ('of', 'IN'),
 ('plants', 'NNS'),
 ('.', '.')]

In [21]:
def lemma_me(sent):
    sentence_tokens1 = nltk.word_tokenize(sent.lower())
    pos_tags1 = nltk.pos_tag(sentence_tokens1)
    
    sentence_lemmas = []
    for token, pos_tag in zip(sentence_tokens1, pos_tags1):
        if pos_tag[1][0].lower() in ['n', 'v', 'a', 'r']:
            lemma1 = lemmatizer.lemmatize(token, pos_tag[1][0].lower())
            sentence_lemmas.append(lemma1)
    
    return sentence_lemmas

In [22]:
l1 = lemma_me("Vegetables are types of plants.")
l1

['duck', 'walk', 'pond']

In [23]:
text = 'Originally, vegetables were collected from the wild by hunter-gatherers. Vegetables are all plants. Vegetables can be eaten either raw or cooked.'
question = 'What are vegetables?' 

In [24]:
sentence_tokens2 = nltk.sent_tokenize(text)
sentence_tokens2.append(question)
sentence_tokens2

['Originally, vegetables were collected from the wild by hunter-gatherers.',
 'Vegetables are all plants.',
 'Vegetables can be eaten either raw or cooked.',
 'What are vegetables?']

In [26]:
tv = TfidfVectorizer(tokenizer=lemma_me)
tv

TfidfVectorizer(tokenizer=<function lemma_me at 0x7efdbeba0670>)

In [27]:
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/pekasus/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /home/pekasus/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [28]:
tf = tv.fit_transform(sentence_tokens2)
tf

<4x8 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [29]:
tf.toarray()

array([[0.27717414, 0.53114624, 0.        , 0.        , 0.53114624,
        0.53114624, 0.        , 0.27717414],
       [0.41988018, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.8046125 , 0.41988018],
       [0.32713399, 0.        , 0.62688384, 0.62688384, 0.        ,
        0.        , 0.        , 0.32713399],
       [0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678]])

In [31]:
import pandas
df = pandas.DataFrame(tf.toarray(), columns=tv.get_feature_names())
df

/home/pekasus/.local/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


be   collect      cook       eat  hunter-gatherer  originally  \
0  0.277174  0.531146  0.000000  0.000000         0.531146    0.531146   
1  0.419880  0.000000  0.000000  0.000000         0.000000    0.000000   
2  0.327134  0.000000  0.626884  0.626884         0.000000    0.000000   
3  0.707107  0.000000  0.000000  0.000000         0.000000    0.000000   

      plant  vegetable  
0  0.000000   0.277174  
1  0.804612   0.419880  
2  0.000000   0.327134  
3  0.000000   0.707107

In [32]:
values = cosine_similarity(tf[-1], tf)
values

array([[0.39198343, 0.59380024, 0.46263733, 1.        ]])

In [33]:
index = values.argsort()[0][-2]
index

1

In [34]:
values_flat = values.flatten()
values_flat

array([0.39198343, 0.59380024, 0.46263733, 1.        ])

In [35]:
coeff = values_flat[-2]
coeff

0.462637331090323

In [ ]:
if coeff > 0.3:
    